# ビルドステージ
FROM node:18.18.0 AS build
WORKDIR /app/
COPY moshmosh/package.json moshmosh/yarn.lock ./ 
RUN yarn install
COPY ./moshmosh .
RUN yarn build

# 実行ステージ
FROM gcr.io/distroless/nodejs
WORKDIR /app
COPY --from=build /app/.next /app/.next
COPY --from=build /app/package.json /app/yarn.lock /app/
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/public /app/public
EXPOSE 3000

# Next.jsの起動
CMD ["node_modules/next/dist/bin/next", "start"]
