on:
  push:
    branches-ignore:
      - "main"
name: Build and Test on Push

env:
  CACHE_KEY_FILE: cache-key.txt

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "${{ runner.os }}-yarn-${{ hashFiles('moshmosh/package.json', 'moshmosh/yarn.lock') }}" > ${{ env.CACHE_KEY_FILE }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: moshmosh/node_modules
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
        working-directory: moshmosh

  run-lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get cache key from setup job
        run: echo "CACHE_KEY=$(cat ${{ env.CACHE_KEY_FILE }})" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: moshmosh/node_modules
          key: ${{ env.CACHE_KEY }}
      - name: Run lint
        run: yarn lint
        working-directory: moshmosh
