on:
  push:
    branches-ignore:
      - "main"
name: Build and Test on Push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calculate cache key
        id: cache-key
        run: echo "cache-key=${{ runner.os }}-yarn-${{ hashFiles('moshmosh/package.json', 'moshmosh/yarn.lock') }}" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: moshmosh/node_modules
          key: ${{ steps.cache-key.outputs.key }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
        working-directory: moshmosh

  run-lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: moshmosh/node_modules
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Run lint
        run: yarn lint
        working-directory: moshmosh

  run-prettier:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Prettier
        run: |
          npm ci
          npx prettier --check ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF
        working-directory: moshmosh

  run-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: moshmosh/node_modules
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Run test
        run: yarn run test
        working-directory: moshmosh
