on:
  push:
    branches-ignore:
      - "main"
name: Build and Test on Push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        run: docker build -f Dockerfile.dev .
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Change working directory
        run: cd moshmosh
      - name: Install Dependencies
        run: yarn install
        working-directory: moshmosh
      - name: Run Test
        run: yarn run test
        working-directory: moshmosh
